#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    minTotal=0
    maxTotal=0
    intCount=1
    arr.sort()
    size=len(arr)
    for x in arr:
        if intCount < size:
            minTotal=minTotal+x
            intCount=intCount+1
            
    intCount=1
    arr.sort(reverse=True)
    for x in arr:
        if intCount < size:
            maxTotal=maxTotal+x
            intCount=intCount+1
    
    print(minTotal, maxTotal)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
