#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    positive = 0
    negative = 0   
    zero = 0
    arrCount = 0
    for x in arr:
        arrCount = arrCount+1
        if x>0:
            positive=positive+1
        elif x<0:
            negative=negative+1
        else:
            zero=zero+1
            
       
    positive=positive/arrCount
    negative=negative/arrCount
    zero=zero/arrCount
   
    print("%.6f" % positive)
    print("%.6f" % negative)
    print("%.6f" % zero)   

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
